### PR TITLE
Fetchurl: update to 17.08

### PR DESCRIPTION
**Pull request by BorisMulder-CSL**
wrapped additional code inside with_libc to prevent crashing with "libc_suspend called [...]" error.

### CODE REVIEW

**Comment by nfeske** [comment]
Thank you Boris! I wonder what is behind the commented-out warning though? If I remember right, @ehmry put it in there as a reminder that the SSL certificates are not actually checked. Has this changed? @ehmry Do you approve the patches?

**Comment by ehmry** [comment]
I would prefer to keep the warning, anytime SSL is in use I would like to assume that the certificates are checked. I would also hope that the warning encourages someone to take on certificate management as a project.

**Comment by BorisMulder-CSL** [comment]
Maybe you should not display this warning when ssl is not used? I was just fetching files with http (no https) and these warnings still popped up even though they are not relevant in this case.

**Comment by ehmry** [comment]
Ah, now I understand.

**Comment by BorisMulder-CSL** [comment]
somehow another commit from my branch has sneaked in, the second one is not supposed to be pulled into genode-world but was made to illustrate issue #2520 on genode.

**Comment by nfeske** [comment]
Fetchurl is now hosted in the main genode repository.

**Pull request closed without merging**
