### PR TITLE
golang support

### PR DESCRIPTION
**Pull request by tor-m6**
initial commit.
this is a support of golang for gcc 10.3 for x86/arm 64 bit using already supplied in toolchain gccgo compiler.
more details in src/test/go_app/README.golang

### CODE REVIEW

**Comment by nfeske** [comment]
Thank you for submitting this impressive line of work. I especially like that you documented the usage and current limitations. While browsing through the commits, the following questions came to mind. I'd appreciate to learn your thoughts about them.

* There is quite some duplication between the port files for libffi, libbacktrace, libgo, and libbacktrace. Each port pulls in a separate copy of gcc. I guess that you decided against using the noux-gcc port because you need to apply custom patches, which is very reasonable. But how do you think about merging the go-related ports into one port file, e.g., named gcc-go_support, to reduce the duplication and storage footprint?

* Commit https://github.com/genodelabs/genode-world/pull/293/commits/da4337223f9d708783b552386562d4a2c51faaba introduces "inno" as a go platform. Given that Genode largely mimics FreeBSD at the libc level, couldn't we live without the addition of a new platform but merely patching the FreeBSB parts that don't work for Genode? If a new platform is needed, why have you decided to name it "inno", not "genode"? I presume that the name comes from Innopolis but I'm a bit puzzled about this distinction when hosting the code at genode-world.

* Several commits contain commented-out code. In Genode's main repository, we generally try to avoid this. In genode-world, we are not strict about it but I'd like to understand your reasoning behind committing such code pieces. Are they meant for illustrative purposes, or are they accidental? Would you like me to merge the commits (including the commended-out parts) as is or would you prefer to remove such dead code from the commits beforehand? Closely related, some files contain file headers copied from elsewhere. E.g., run/go_http_lx.run states that I'm the author of this file, which I'm not. I'd prefer accurate attribution of work. In this particular case, you would be the author and the file header could state that the file is based on [...].

* I noticed that you follow our practice of adding a nice file header to each source code file, which is good to see. But you decided against putting licensing information there (e.g., the files at `lib/libgo_support/`). This raises the question of what are the licensing conditions of this code and where can a user learn about them? E.g., if your intention is to inherit the gcc licensing conditions wherever appropriate, it would be sensible to clearly document this intention, preferably at the file headers, or in the form of an accompanied LICENSE file.

* Would you be fine with prefixing the first line of each commit message with "go: " so that commit history becomes easier to assess?

**Comment by tor-m6** [comment]
> 
> * There is quite some duplication between the port files for libffi, libbacktrace, libgo, and libbacktrace. Each port pulls in a separate copy of gcc. I guess that you decided against using the noux-gcc port because you need to apply custom patches, which is very reasonable. But how do you think about merging the go-related ports into one port file, e.g., named gcc-go_support, to reduce the duplication and storage footprint?

In general, I agree - while to build 3 separate target each with own configure in single port is a bit tricky for me, I need good samples. 
While there are not a full copy - port take just appropriate lib dir from distribution plus dozen of support file in upper directory which are copied (together with the main gcc...gz file).
Reason for existence of 3 copy of these libs which is partially coincide with general tools gcc libs and some other ports (e.g. ffi) is that they are taken from gcc core distribution which is different from others, should be taken exactly from the same gcc version and build of libgo require some headers from them.

> * Commit [da43372](https://github.com/genodelabs/genode-world/commit/da4337223f9d708783b552386562d4a2c51faaba) introduces "inno" as a go platform. Given that Genode largely mimics FreeBSD at the libc level, couldn't we live without the addition of a new platform but merely pretending that Genode is FreeBSB and patching the FreeBSB parts that don't work for Genode? If a new platform is needed, why have you decided to name it "inno", not "genode"? I presume that the name comes from Innopolis but I'm a bit puzzled about this distinction when hosting the code at genode-world.

initially I try to base the port on NetBSD as simplest, and always try to find FreeBSD port for functions from libraries. FreeBSD itself too complex and has too many options which are not implemented in Genode. For such staff I need to patch it out, and volume of changes became too big, so, I choose to have a mix of FreeBSD/Linux/etc based on Netbsd.
on every new genode release I try to find may be some new sys calls/libc functions became available.

Naming is a result of history - initially this port was intended for a different project where we should implement docker containers support on some new microkernel OS (and whole infrastructure for docker are written in go which I have to port), and we do name it indeed as  inno referencing our university. Only later it appears as related to genode. Of course, it could be renamed easily, I will make it. 

> * Several commits contain commented-out code. In Genode's main repository, we generally try to avoid this. In genode-world, we are not strict about it but I'd like to understand your reasoning behind committing such code pieces. Are they meant for illustrative purposes, or are they accidental? Would you like me to merge the commits (including the commended-out parts) as is or would you prefer to remove such dead code from the commits beforehand? Closely related, some files contain file headers copied from elsewhere. E.g., run/go_http_lx.run states that I'm the author of this file, which I'm not. I'd prefer accurate attribution of work. In this particular case, you would be the author and the file header could state that the file is based on [...].

I can miss something while I try to remove experimental code. 
Anyway, Typically there are 2 kinds of comments: related to build options (like "// build netbsd" - definitely to must) and some code I which I should to kill because I need to replace them.
I choose to keep some portion of old code for simple reason: if something do not work properly after my patches - it will be helpful to understand what original code does if you trace till them (e.g. random generator related code/etc, existence of these comments save me time when I fix it).
if you find anything else - probably it could be eliminated.
The only significant place with commented code was a set of general code for Go which I use as a test (I put them into main.go file and comment other examples for simplicity, they are separated by line "package main").

and, of course, I borrowed code from genode samples, sometimes together with copyright. This should be fixed somehow, I completely agree - my fault, now I even not sure which origin I used  (and I mostly take a look for code and forget about other files). Will good to fix this. 

> * I noticed that you follow our practice of adding a nice file header to each source code file, which is good to see. But you decided against putting licensing information there (e.g., the files at `lib/libgo_support/`). This raises the question of what are the licensing conditions of this code and where can a user learn about them? E.g., if your intention is to inherit the gcc licensing conditions wherever appropriate, it would be sensible to clearly document this intention, preferably at the file headers, or in the form of an accompanied LICENSE file.

Most of my code do not developed from the scratch, I borrow samples from gcc distribution, libc FreeBSD port, Genode main and contributed code (probably the only clear mine code is related to mmap support, while it also based on java genode port approaches and structures - partially).
Probably as you state it should have the same license as other code (GPL2 as gcc?) while I suspect that some code can have something like BSD license as well. Any suggestions how to place it correctly? refer to general Genode license in every header?

> * Would you be fine with prefixing the first line of each commit message with "go: " so that the commit history becomes easier to assess?

ok, I do not see any problems.

**Comment by nfeske** [comment]
Thank you for the detailed response and for considering my remarks.

It is good to know your rationale behind the addition of the new platform.

Don't worry too much about my question about the duplicated content of the port files. We can always decide to consolidate them into a single port at a later time.

Regarding the license for the runtime, I'd intuitively recommend sticking with the license as used by GCC's runtime libraries, which is an established pattern. When you grep in GCC's source tree for "COPYING.RUNTIME", there are many examples that you could use as blueprint for the file header of your files. For files that are based on existing code like FreeBSD's libc, it is sensible to inherit the license header of the original file. This avoids any friction when potentially backporting code from the derived file to the original file any time in the future.

**Comment by tor-m6** [comment]
> Don't worry too much about my question about the duplicated content of the port files. We can always decide to consolidate them into a single port at a later time.
> 
cf7f3ba85b85b50c3aa9e6110322efee92e93271 commit consolidate 4 ports of libs into single one. please check.
the only problem that I can't make directly libgo, I shoud build first manually libatomic/etc as described in REAMDE (it just start MERGE archive without build and fail)

**Comment by tor-m6** [comment]
In [16c292a](https://github.com/genodelabs/genode-world/pull/293/commits/16c292a3163d97bdecd6bb59560a4c335872e0cb) patch I try to introduce BSD-like license for support libs. One potential problem - file https://github.com/tor-m6/genode-world/blob/22.05/src/lib/libgo_support/file_operations_anon.cc is derived from Genode framework one covered by GPL3 and had some other code under BSD... Do not sure that this is correct.
In code related to platform I had a nice mix of files with LGPL and BSD licenses (separately).

**Comment by nfeske** [comment]
Thanks a lot for the careful rework.

In commit https://github.com/genodelabs/genode-world/pull/293/commits/7d1eb5c9d4bfafbf3faba4a2fe1b7e209af3c375, you added the licensing header, including the line:

> Contributed by Andreas Jaeger <aj@suse.de>, 2002.

I wondered, is this intentional? Just double-checking.

Thanks to your latest modifications, the current state looks very nice. Now, in order to merge the work, I'd appreciate you pushing a clean branch with the rework/cleanup/licensing commits squashed into the respective original commits (using `git rebase -i`), and with all commit titles marked with the "go:" prefix. Please try to keep commit titles small (max of 50 characters).

With this rebasing step, only tidy commits of your work will remain visible at the master branch of genode-world. The number of commits is up to you - depending on the granularity you'd like to preserve in the master branch. I recommend manually skimming though the commits just to go sure that no major glitches remain and that each commit on its own is a wholesome change (if reviewed by a 3rd party).

Once I get hold of your updated branch, I'll do some testing before merging the work. At this point, I will possibly come up with a suggestion for the remaining issue about the manual libatomic/etc step.

**Comment by tor-m6** [comment]
> In commit [7d1eb5c](https://github.com/genodelabs/genode-world/commit/7d1eb5c9d4bfafbf3faba4a2fe1b7e209af3c375), you added the licensing header, including the line:
> 
> > Contributed by Andreas Jaeger [aj@suse.de](mailto:aj@suse.de), 2002.
> 
> I wondered, is this intentional? Just double-checking.
> 

yes, this is from context switch x86 code from glibc (while I removed it from arm files - he is not an author, it just has a general license).

> Thanks to your latest modifications, the current state looks very nice. Now, in order to merge the work, I'd appreciate you pushing a clean branch with the rework/cleanup/licensing commits squashed into the respective original commits (using `git rebase -i`), and with all commit titles marked with the "go:" prefix. Please try to keep commit titles small (max of 50 characters).
> 
done with minimal set of patches: https://github.com/tor-m6/genode-world/commits/22.05clean

**Comment by nfeske** [comment]
Thanks for the tidy branch, which I merged to staging now.

Note that I tagged all commits with issue number 293 so that they appear in the timeline of this issue.

While skimming through the commits, I noticed that there are still some occurrences of "inno".

Upon giving the run/go_app a quick try, I somewhat failed at the `make lib/libgo` step:
```
    BUILD    libgo
      [libgo]  /bin/bash: -d: invalid option
      [libgo]  Usage:	/bin/bash [GNU long option] [option] ...
...
... bash usage information follows ...
...
      [libgo]  libtool: compile: unrecognized option `-minline-all-stringops'
      [libgo]  libtool: compile: Try `libtool --help' for more information.
      [libgo]  Makefile:2866: recipe for target 'internal/cpu.lo' failed
      [libgo]  make[5]: *** [internal/cpu.lo] Error 1
```

May this effect be related to my host system (an admittedly fairly dated Ubuntu 18.04)?

Have you considered moving the magic of the `installed_tar.tag:` rules from the `src/lib/*/target.mk` files to the respective `lib/mk/*` files using the `CUSTOM_TARGET_DEPS` hook? (see https://genode.org/documentation/genode-foundations/22.05/development/Build_system.html#Custom_targets_accompanying_a_library_or_program) This way, the symlinks to the archives would be created immediately at the build time of the library not as a side effect of any `target.mk` file. So since `go_app/target.mk` has `libgo` specified in `LIBS`, the symlinks would be created before the `go_app` target gets built.

**Comment by tor-m6** [comment]
> 
> While skimming through the commits, I noticed that there are still some occurrences of "inno".
> 
Sorry - by bad, I forget completely about renaming (Freudian slip? remove own project name ;))), will be separate cosmetic patch

> Upon giving the run/go_app a quick try, I somewhat failed at the `make lib/libgo` step:
> 
> ```
>     BUILD    libgo
>       [libgo]  /bin/bash: -d: invalid option
>       [libgo]  Usage:	/bin/bash [GNU long option] [option] ...
> ...
> ... bash usage information follows ...
> ...
>       [libgo]  libtool: compile: unrecognized option `-minline-all-stringops'
>       [libgo]  libtool: compile: Try `libtool --help' for more information.
>       [libgo]  Makefile:2866: recipe for target 'internal/cpu.lo' failed
>       [libgo]  make[5]: *** [internal/cpu.lo] Error 1
> ```
> 
> May this effect be related to my host system (an admittedly fairly dated Ubuntu 18.04)?

I suppose that this is related to setup of env variables which configure script do inherit from the shell (and of course they should be in the PATH). It explained in [README.golang,](https://github.com/tor-m6/genode-world/blob/22.05clean/src/test/go_app/README.golang) typically you need some script like

#!/bin/sh
ARCH=aarch64
PARCH=arm_v8a
#ARCH=x86
#PARCH=x86_64
export GOC=genode-$ARCH-gccgo
export GDB=genode-$ARCH-gdb
export CXX=genode-$ARCH-c++
export LD=genode-$ARCH-ld
export READELF=genode-$ARCH-readelf
export AR=genode-$ARCH-ar
export AS=genode-$ARCH-as
export NM=genode-$ARCH-gcc-nm
export GCC=genode-$ARCH-gcc
export OBJCOPY=genode-$ARCH-objcopy
export STRIP=genode-$ARCH-strip
export OBJDUMP=genode-$ARCH-objdump
export PATH=/usr/local/genode/tool/current/bin:<your genode dir>/build/$PARCH/lib/libgo:$PATH
export CC=genode-$ARCH-gcc
export RANLIB=genode-$ARCH-ranlib

and execute file above like '. ./pathes.sh'
probably this is a source of the problem. I use genode docker build container with tools where I setup such variables.

Also as a part of build of additional "goroot" port you need host native gcc, including gccgo (to build cross tools for go). Better to use them from similar version, like 10.3. I think that you probably not build this port before (goroot is not required for basic tests/libgo, this is natural way for go projects and I use it to build complex projects on top, like docker for genode support runc project which is my focus of interest).

> 
> Have you considered moving the magic of the `installed_tar.tag:` rules from the `src/lib/*/target.mk` files to the respective `lib/mk/*` files using the `CUSTOM_TARGET_DEPS` hook? (see https://genode.org/documentation/genode-foundations/22.05/development/Build_system.html#Custom_targets_accompanying_a_library_or_program) This way, the symlinks to the archives would be created immediately at the build time of the library not as a side effect of any `target.mk` file. So since `go_app/target.mk` has `libgo` specified in `LIBS`, the symlinks would be created before the `go_app` target gets built.

 not yet, will try. this is gcc own build system (configure/etc) artefacts, not mine. Assume just marks that some of libs builds finished from inside other libs build, not anyhow related to the tar archives. I will think what I should do... initially it was just fast fix by our devops, and, as usual, still exists.

**Comment by tor-m6** [comment]
> > While skimming through the commits, I noticed that there are still some occurrences of "inno".
> 
> Sorry - my bad, I forget completely about renaming (Freudian slip? remove own project name ;))), will be separate cosmetic patch
> 
pushed rename patch for inno -> genode to https://github.com/tor-m6/genode-world/commits/22.05clean

**Comment by nfeske** [comment]
> pushed rename patch for inno -> genode

That is very much appreciated. I cherry-picked your patch to staging. While doing that, I noticed your other patch 8b5941e801528f80cb439546d659946a32b2eb8d, which is a very welcome change. Should I merge this one to staging as well?

**Comment by chelmuth** [comment]
The work in this PR was merged to master. For further contributions, please open a new Issue/PR.

**Pull request closed without merging**
