### PR TITLE
Python3 fixes

### PR DESCRIPTION
**Pull request by ValiValpas**

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks for the welcome update, which I merged into master right away. With the changes, Python3 is ready to use in Sculpt now, isn't it? Really cool!

**Comment by ValiValpas** [comment]
It still requires the libc patch as mentioned in https://github.com/genodelabs/genode/pull/2867. 

I'll provide a deployable depot pkg soon.

**Comment by ValiValpas** [comment]
For the record, I just pushed the sculpt-ready recipes to a new branch. I suggest the following: Once the libc patch hits the master branch, I'll update the hashes and create a new pull request.

https://github.com/ValiValpas/genode-world/commit/b8d4784158a0af66c0da357670542fd83ad5b5f3

**Comment by nfeske** [comment]
Today, the `clock_getres` entered Genode's master branch.

**Pull request closed without merging**
