### PR TITLE
Remoterom

### PR DESCRIPTION
**Pull request by ValiValpas**
Implements a proxy component for ROM sessions. The proxy implementation is intended to be modular for which it defines a backend interface. There is currently a single backend which translates the ROM session into IP packets using the nic_session.

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks for the pull request. Bu it leaves me a little confused. The patch series contains patches that are unrelated to the topic of the pull request. Some of them are already present in our master branch. Could you please post a topic branch with only the relevant commits rebased on top of the master branch of genodelabs/genode-world?

Regarding the actual topic, would you mind renaming `remoterom` to `remote_rom` to be consistent with the regular way of how we name components?

**Comment by ValiValpas** [comment]
I added a new branch `remote_rom` for this.

**Comment by nfeske** [comment]
Thank you very much! This looks great and very polished (including a README, and run scripts). As a minor remark, would you mind adding a license notice to the source-file headers?

**Comment by ValiValpas** [comment]
@nfeske done ;-)

**Comment by nfeske** [comment]
Thanks for the quick response! I have merged it (as a single commit) to master.

**Pull request closed without merging**
