### PR TITLE
go: consolidate additional libs to single port for 22.11

### PR DESCRIPTION
**Pull request by tor-m6**
make golang working with genode release 22.11 and simplify building process

### CODE REVIEW

**Comment by tor-m6** [comment]
Added "go build" host tool to toolchain to allow automatic download and compilation of go packages from inside build system.

Also consolidate and cleanup some run files to simplify development of go programs with network, update README.

**Comment by nfeske** [comment]
Thank you for the additional commits, which I merged to staging just now.

**Comment by tor-m6** [comment]
probably docker -related commits are too early to apply to staged, I just finish dirty compilation and do not try to run. I still need some other binaries to be compiled and assembled (containerd docker docker-cli) before starting excersises with docker ontop of genode.

**Comment by nfeske** [comment]
Thank you for the heads-up. I removed this commit from staging.

**Comment by nfeske** [comment]
I must admit that I lost track about which commits should best be picked up for staging.

@tor-m6 could you provide me with a bit of guidance? Or can you prepare a `merge_to_staging` branch for me that contains the series of commits you wish to be merged?

**Comment by tor-m6** [comment]
sorry, this is kind of mess, these patches not suitable for staging, I will make a separate branch as suggested.

Problem that now I second time encounter situation that after patches suggested by @cproc I appears in the situation that it start to generate recursive definition in libdeps which fail (before it was also some endless generation of recursive make calls, not clear why ).
like
``
DEP_A_libgo  = ${ARCHIVE_NAME(libgo)} $(DEP_A_libgo) ${ARCHIVE_NAME(libgo_support)} $(DEP_A_libgo_support) ${ARCHIVE_NAME(libatomic)} $(DEP_A_libatomic) ${ARCHIVE_NAME(libbacktrace)} $(DEP_A_libbacktrace) ${ARCHIVE_NAME(libffi)} $(DEP_A_libffi) ${ARCHIVE_NAME(posix)} $(DEP_A_posix)
DEP_SO_libgo = ${SO_NAME(libgo)} $(DEP_SO_libgo) ${SO_NAME(libgo_support)} $(DEP_SO_libgo_support) ${SO_NAME(libatomic)} $(DEP_SO_libatomic) ${SO_NAME(libbacktrace)} $(DEP_SO_libbacktrace) ${SO_NAME(libffi)} $(DEP_SO_libffi) ${SO_NAME(posix)} $(DEP_SO_posix)``

I suspect that the origin of both problems is the same. 
Moreover, it apperars not immediately, it works in fresh system ok, until something happens after a lot of make invocations - and not clear what, it change behaviour after small cosmetic changes and not revert to normal after rollback... strange. Kind of export variables/etc problems, may be.

**Comment by nfeske** [comment]
Thank you for the clarification with regard to merging.

**Pull request closed without merging**
