### PR TITLE
remote_rom and zynq_boards improvements + udp_log/log_udp proxies

### PR DESCRIPTION
**Pull request by ValiValpas**
First, there are some necessary updates for the zynq board specs.

Second, there have been some improvements for the remote_rom proxy.

Third, there are two new proxy components: udp_log and log_udp that can be used to relay a LOG session (e.g. on a headless device) to another machine. It uses UDP with static IP addresses.

### CODE REVIEW

**Comment by chelmuth** [comment]
:+1: for the UDP log which will bedome very handy

**Comment by nfeske** [comment]
Thanks for this profound update, @ValiValpas! I merged your commit series.

It's especially great to @3dik's changes of the remote-rom mechanism, which take our C++ programming style by heart.

I applaud your fantastic job in maintaining the Zynq and remote-rom topics in such a consistent manner. I think, for the Genode community at large, it would be quite intriguing to learn more about the background of this work. Have you already considered to bring attention to it, i.e., in the form of an overview article at genodians.org? I sense that you are taking Genode to a pretty unique direction. Hence, your insights and experiences are certainly valuable for others.

**Comment by ValiValpas** [comment]
@nfeske Thank you very much for your appreciation. Actually, I am considering bringing attention to this work. I'm still unsure about how to present it but there will hopefully emerge some clarity in my head as I'm currently wrapping up and writing my thesis anyway.

**Comment by nfeske** [comment]
@ValiValpas All the best for your thesis then! (I vividly remember the pain) ;-)

**Pull request closed without merging**
