### PR TITLE
add ports (glucose, lemon, soplex, scip)

### PR DESCRIPTION
**Pull request by ValiValpas**

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks for the ports. I squashed the fixups into there corresponding initial commit and renamed the run script from `test-<name>.run` to just `<name>.run` since the run scripts are test anyway. There is no need to name them as such. @ValiValpas: Hope that's ok?

**Comment by ValiValpas** [comment]
Yes, that's okay. This naming scheme is just a habit of mine to distinguish the interactive run scripts from run scripts that are suitable for automated testing.

**Comment by nfeske** [comment]
Good point. We actually plan to make this distinction by introducing a dedicated repository "repos/attic" that hosts all the sporadically used interactive run scripts. All the run scripts found in the regular repositories should eventually become runnable as automated test.

**Comment by nfeske** [comment]
I'm closing this issue since the commits are merged in master.

**Pull request closed without merging**
