### PR TITLE
ported iperf2 to genode, run script based on netperf run scripts

### PR DESCRIPTION
**Pull request by rolandbaer**
I've ported iperf2 to genode. The run scripts are based on the netperf run scripts, but not all variants are included.

### CODE REVIEW

**Comment by nfeske** [comment]
Thank you @rolandbaer for this welcome contribution!

I merged your commit with a slightly adjusted commit message (adhering to the 50-character limit of the first line, mentioning this issue number) to master.

**Comment by nfeske** [comment]
@rolandbaer I'm currently working on the release notes for the upcoming Genode version 20.08. I wonder, would you like to have your contribution mentioned and credited in the release notes?

If yes, I would very much appreciate a short paragraph about the new feature. E.g., a few words about what motivated you to add it and how it can be used. What do you think?

**Comment by rolandbaer** [comment]
@nfeske I don't think it is really needed to be mentioned or credited in the release notes. It was for me a small holiday evenings project to get my hands dirty with porting a tool to genode that I'm familliar with.

**Comment by nfeske** [comment]
Thanks for the response. It's nice to know that Genode played a role in sweetening your holiday evening. ;-)

**Pull request closed without merging**
